# -*- coding: utf-8 -*-
"""YoloV3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14lhEKIaIzg0GJOnmEfq2PbbTjFHTIX8E

# **Alternate Method**
"""

!git clone https://github.com/pjreddie/darknet

# Commented out IPython magic to ensure Python compatibility.
# %cd darknet

!make

!wget https://pjreddie.com/media/files/yolov3.weights

!./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg

!./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg